CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers(
id INTEGER(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
devoured BOOLEAN DEFAULT false,
createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);